"""followers

Revision ID: 606694f9cb51
Revises: 46f17a60f179
Create Date: 2019-12-08 19:40:21.336909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606694f9cb51'
down_revision = '46f17a60f179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
